name: Build
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: ESLint
              run: npm run eslint
            - name: Prettier lint
              run: npm run prettier-lint
            - name: Stylelint
              run: npm run stylelint
            - name: HTMLHint
              run: npm run htmlhint
            - name: Run tests
              run: npm run test-headless
